name: Tracker CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "tracker/**"

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm --prefix ./tracker ci --force
      - name: Install Playwright Browsers
        working-directory: ./tracker
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm --prefix ./tracker test
      - name: Upload replays
        if: ${{ always() }}
        uses: replayio/action-upload@v0.5.1
        with:
          public: true
          api-key: rwk_J4V7IDVzZIZTZY1xgo2XshOf01NK2lYZdsVvalnEhJ7
